
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useRef, useEffect } from 'react';
import { QrReader } from '@blackbox-vision/react-qr-reader';

const qrStyle = {
  //zIndex: 1,
  width: "100vw",
  // width: "65vw",
  //height: "100vh",
  top: "0",
  left: "0",
  overflowY: "hidden",
  overflowX: "hidden",
  objectFit: "cover"
  //position: "static"
};


export default function Home() {


  const [data, setData] = useState("No result");
  const [facingMode, setFacingMode] = useState("environment");
  const [isQrShown, setIsQrShown] = useState(true);
  const [isCameraOpen, setIsCameraOpen] = useState(true);

  const changeFacingMode = () => {
    facingMode === "user"
      ? setFacingMode("environment")
      : setFacingMode("user");

    setIsQrShown(false);
  };

  useEffect(() => {
    setIsQrShown(true);
  }, [isQrShown]);

  const changeQrView = () => {
    setIsQrShown(() => !isQrShown);
  };
  useEffect(() => {
    (async function effectDetectCamera() {
      // await detectCamera();
    })();
    // if (userData !== "yes") {
    //   (async function effectDetectCamera() {
    //     await detectCamera();
    //   })();
    // } else setPermissionGranted(true)
  }, []);



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}><a href="https://nextjs.org">Qr scner</a>
        </h1>
        <button onClick={changeFacingMode}>change camera </button>
      <button onClick={changeQrView}>change view </button>
      {isQrShown && isCameraOpen && (
        <QrReader
          onResult={(result, error) => {
            if (!!result) {
              setData(result?.text);
            }

            if (!!error) {
            }
          }}
          style={{ width: "100%" }}
          videoContainerStyle={qrStyle}
          scanDelay={100}
          videoStyle={{ height: "auto" }}
          constraints={{ facingMode: facingMode }}
        />
      )}

      <p>{data}</p>
        </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
